import {test,expect} from '@playwright/test';
import {newSite} from '../../lib/model';
function tone(hz:number){const rate=16000,length=rate*8,b=Buffer.alloc(44+length*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVE',8);b.write('fmt ',12);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(length*2,40);for(let i=0;i<length;i++)b.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*hz/rate)*6000),44+i*2);return b;}
test('default disco follows real bass, toggles independently, and stops with pause/mute',async({page,request})=>{
 test.skip(!process.env.MIDNIGHT_ONLINE_TEST,'Requires native sharing.');
 const base=process.env.MIDNIGHT_TEST_BASE_URL!,site=newSite(),origin=new URL(base).origin,headers={Authorization:'Bearer '+crypto.randomUUID()+crypto.randomUUID(),Origin:origin};
 expect((await request.post('/api/sharing/'+site.id,{headers})).status()).toBe(200);
 try{
  const sources:string[]=[];for(const hz of [100,4000]){const bytes=tone(hz),r=await request.put('/api/sharing/'+site.id+'/media/'+crypto.randomUUID(),{headers:{...headers,'Content-Type':'audio/wav','Content-Length':String(bytes.length)},data:bytes});expect(r.status(),await r.text()).toBe(200);sources.push((await r.json()).url);}
  site.music=sources[0];site.chapters[0].media=[{id:crypto.randomUUID(),kind:'audio',src:sources[1],caption:'Treble test',x:50,y:50,zoom:1}];expect((await request.put('/api/sharing/'+site.id,{headers,data:site})).status()).toBe(200);
  await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('/s/'+site.id);const toggle=page.getByRole('switch',{name:'Disco lights',includeHidden:true}),canvas=page.locator('.disco-lights');await expect(toggle).toHaveAttribute('aria-checked','true');await expect(canvas).toHaveAttribute('data-active','false');await page.getByRole('button',{name:'Draw the curtains'}).click();await expect.poll(()=>canvas.getAttribute('data-bass')).not.toBe('0');await expect.poll(async()=>Number(await canvas.getAttribute('data-bass'))).toBeGreaterThan(.15);await expect(page.getByRole('dialog',{name:'Birthday premiere'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'work/disco-lights-mobile.png'});
  await toggle.click();await expect(canvas).toHaveAttribute('data-active','false');expect(await page.locator('.audio-soundtrack audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBe(false);await toggle.click();await expect(canvas).toHaveAttribute('data-active','true');await expect.poll(async()=>Number(await canvas.getAttribute('data-bass'))).toBeGreaterThan(.15);
  await page.getByLabel('Change music').selectOption('1');await expect.poll(()=>page.locator('.audio-soundtrack audio').evaluate((a:HTMLAudioElement)=>a.currentTime)).toBeGreaterThan(.5);await expect.poll(async()=>Number(await canvas.getAttribute('data-bass'))).toBeLessThan(.05);
  await page.getByLabel('Change music').selectOption('0');await expect.poll(async()=>Number(await canvas.getAttribute('data-bass'))).toBeGreaterThan(.15);await page.getByRole('button',{name:'Mute music',exact:true}).click();await expect(canvas).toHaveAttribute('data-active','false');await page.getByRole('button',{name:'Unmute music',exact:true}).click();await page.getByRole('button',{name:'Pause music',exact:true}).click();await expect(canvas).toHaveAttribute('data-active','false');await page.getByRole('button',{name:'Play music',exact:true}).click();await page.emulateMedia({reducedMotion:'reduce'});await expect(canvas).toHaveAttribute('data-reduced-motion','true');expect(await canvas.evaluate(el=>getComputedStyle(el).pointerEvents)).toBe('none');
 }finally{await request.post('/api/sharing/'+site.id+'?action=unpublish',{headers});}
});
