import {test,expect} from '@playwright/test';
import {newSite} from '../../lib/model';
import {PNG} from 'pngjs';
function photo(n:number){const png=new PNG({width:480,height:600});for(let y=0;y<600;y++)for(let x=0;x<480;x++){const p=(y*480+x)*4;png.data[p]=80+n*20+Math.round(y/8);png.data[p+1]=100+Math.round(x/6);png.data[p+2]=155+n*10;png.data[p+3]=255;}return PNG.sync.write(png);}
test('all gifts get ambient lights without music and an asymmetric accessible memory gallery',async({page,request})=>{
 test.skip(!process.env.MIDNIGHT_ONLINE_TEST,'Requires native sharing.');const base=process.env.MIDNIGHT_TEST_BASE_URL!,site=newSite(),origin=new URL(base).origin,headers={Authorization:'Bearer '+crypto.randomUUID()+crypto.randomUUID(),Origin:origin};expect((await request.post('/api/sharing/'+site.id,{headers})).status()).toBe(200);
 try{for(let i=0;i<6;i++){const id=crypto.randomUUID(),r=await request.put('/api/sharing/'+site.id+'/media/'+id,{headers:{...headers,'Content-Type':'image/png'},data:photo(i)});expect(r.status(),await r.text()).toBe(200);site.chapters[5].media.push({id,kind:'image',src:(await r.json()).url,caption:'Sample memory '+(i+1),x:i===0?25:50,y:50,zoom:i===0?1.4:1});}expect((await request.put('/api/sharing/'+site.id,{headers,data:site})).status()).toBe(200);
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/s/'+site.id);await page.getByRole('button',{name:'Draw the curtains'}).click();await expect(page.locator('.ambient-lighting')).toHaveAttribute('data-enabled','true');await expect(page.getByRole('switch',{name:'Disco lights'})).toHaveAttribute('aria-checked','true');await expect(page.getByText('Ambient aurora',{exact:false})).toBeVisible();expect(await page.locator('.audio-soundtrack audio').count()).toBe(0);await page.getByRole('switch',{name:'Disco lights'}).click();await expect(page.locator('.ambient-lighting')).toHaveAttribute('data-enabled','false');await page.getByRole('switch',{name:'Disco lights'}).click();
 const photos=page.locator('.memory-print');await expect(photos).toHaveCount(6);await expect.poll(()=>photos.first().locator('img').evaluate((i:HTMLImageElement)=>i.naturalWidth)).toBe(480);expect(await photos.first().locator('img').evaluate(i=>getComputedStyle(i).objectPosition)).toBe('25% 50%');await photos.nth(1).click();const dialog=page.getByRole('dialog',{name:'Memory photo viewer'});await expect(dialog).toBeVisible();await expect(dialog.locator('figcaption')).toHaveText('Sample memory 2');await page.keyboard.press('ArrowRight');await expect(dialog.locator('figcaption')).toHaveText('Sample memory 3');await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(photos.nth(1)).toBeFocused();await photos.first().click();await dialog.getByRole('button',{name:'Previous memory photo'}).click();await expect(dialog.locator('figcaption')).toHaveText('Sample memory 6');await dialog.getByRole('button',{name:'Close photo viewer'}).click();
 await page.locator('.memory-wall').scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'work/gallery-aurora-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.locator('.memory-wall').scrollIntoViewIfNeeded();const boxes=await photos.evaluateAll(elements=>elements.slice(0,3).map(el=>({x:el.getBoundingClientRect().x,y:el.getBoundingClientRect().y,width:el.getBoundingClientRect().width})));expect(boxes[0].width).toBeGreaterThan(boxes[1].width);expect(boxes[2].y).toBeGreaterThan(boxes[0].y+100);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'work/gallery-aurora-desktop.png'});
 await page.emulateMedia({reducedMotion:'no-preference'});await page.reload();await page.getByRole('button',{name:'Draw the curtains'}).click();await photos.first().scrollIntoViewIfNeeded();await expect(photos.first()).toHaveClass(/memory-arrived/);expect(await photos.first().evaluate(el=>getComputedStyle(el).animationName)).toBe('memoryFloat');await photos.first().click();expect(await dialog.locator('figure').evaluate(el=>getComputedStyle(el).animationName)).toBe('memoryFocus');await page.emulateMedia({reducedMotion:'reduce'});expect(await dialog.locator('figure').evaluate(el=>getComputedStyle(el).animationName)).toBe('none');
 }finally{await request.post('/api/sharing/'+site.id+'?action=unpublish',{headers});}
});
