import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs/promises';
import {newSite} from '../../lib/model';
test('living themes, stars, editable cartoon, clocks, keepsake, soundtrack and sealed capsule',async({page,browser,request})=>{
 test.skip(!process.env.MIDNIGHT_ONLINE_TEST,'Requires native sharing.');
 const base=process.env.MIDNIGHT_TEST_BASE_URL!;const origin=new URL(base).origin;const local=new URL(base).hostname==='127.0.0.1';
 const site=newSite();site.recipient='Sample recipient';site.date='2000-12-31T00:00';site.chapters[4].text='The first shared hello\nA walk beneath the stars';site.chapters[2].text='May your next year be full of little wonders.';site.youtubeSongs=['https://youtu.be/M7lc1UVf-VE','https://www.youtube.com/watch?v=jNQXAC9IVRw'];
 const token=crypto.randomUUID()+crypto.randomUUID();const own={Authorization:'Bearer '+token,Origin:origin};
 async function api(method:string,url:string,options:Parameters<typeof request.fetch>[1]={}){for(let i=0;i<3;i++){const r=await request.fetch(url,{...options,method});if(r.status()!==503||!(await r.text()).includes('worker restarted')||i===2)return r;}throw new Error('Preview unavailable');}
 expect((await api('POST','/api/sharing/'+site.id,{headers:own})).status()).toBe(200);expect((await api('PUT','/api/sharing/'+site.id,{headers:own,data:site})).status()).toBe(200);
 await page.goto('/');await page.evaluate(({site,token})=>{localStorage.setItem('mm-drafts',JSON.stringify([site]));localStorage.setItem('mm-publication-key-'+site.id,token);localStorage.setItem('mm-online-'+site.id,'1');},{site,token});await page.reload();await page.getByRole('button',{name:'Open editor'}).click();await page.getByRole('button',{name:'Style',exact:true}).click();await page.getByLabel('Birthday & meeting timezone').selectOption('Asia/Kolkata');await page.getByLabel('Our first meeting date & time').fill('2020-01-02T12:30');await page.getByLabel('Character 1 name').fill('One');await page.getByLabel('Character 2 name').fill('Two');await page.getByLabel('Cartoon scene 1').fill('Our first hello at the grocery store.');await page.getByLabel('Cartoon scene 2').fill('A train ride together.');await page.getByLabel('Recipient login email').fill('recipient@example.test');await page.getByRole('button',{name:'Save password & diary settings'}).click();await expect(page.getByText('Access settings saved online.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Media',exact:true}).click();const pcm=Buffer.alloc(44+8000*2*4);pcm.write('RIFF');pcm.writeUInt32LE(pcm.length-8,4);pcm.write('WAVE',8);pcm.write('fmt ',12);pcm.writeUInt32LE(16,16);pcm.writeUInt16LE(1,20);pcm.writeUInt16LE(1,22);pcm.writeUInt32LE(8000,24);pcm.writeUInt32LE(16000,28);pcm.writeUInt16LE(2,32);pcm.writeUInt16LE(16,34);pcm.write('data',36);pcm.writeUInt32LE(pcm.length-44,40);for(let i=0;i<32000;i++)pcm.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*220/8000)*500),44+i*2);for(const name of ['First tune.wav','Second tune.wav']){await page.locator('.upload input[type=file]').setInputFiles({name,mimeType:'audio/wav',buffer:pcm});await expect(page.locator('progress')).toHaveCount(0);}await page.getByRole('button',{name:'Publish online',exact:true}).click();await expect(page.getByText('Published snapshot created.',{exact:false})).toBeVisible();
 const snapshot=await (await api('GET','/api/sharing/'+site.id)).json();expect(snapshot.youtubeSongs).toHaveLength(2);expect(snapshot.comicScenes[0]).toContain('grocery');expect(snapshot.music).toContain('/media/');expect(snapshot.chapters.flatMap((c:{media:{kind:string}[]})=>c.media).filter((m:{kind:string})=>m.kind==='audio')).toHaveLength(1);expect(snapshot.timeZone).toBe('Asia/Kolkata');
 const visitor=await browser.newContext({baseURL:base,viewport:{width:390,height:844},reducedMotion:'reduce'});
 const view=await visitor.newPage();await view.goto('/s/'+site.id);expect(await view.locator('.audio-soundtrack audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBe(true);await view.getByRole('button',{name:'Draw the curtains'}).click();const firstWorld=await view.locator('.world-label span').textContent();await view.reload();await view.getByRole('button',{name:'Draw the curtains'}).click();expect(await view.locator('.world-label span').textContent()).not.toBe(firstWorld);await view.getByRole('button',{name:'Memory star 2',exact:true}).click();await expect(view.locator('.star-memory')).toContainText('A walk beneath the stars');await expect(view.locator('.cartoon-screen')).toHaveClass(/scene-shop/);await expect(view.locator('.comic-book p')).toHaveCount(0);await view.getByRole('button',{name:'Next cartoon scene'}).click();await expect(view.locator('.cartoon-screen')).toHaveClass(/scene-train/);await expect(view.getByRole('heading',{name:'Until your next birthday.'})).toBeVisible();await view.getByRole('button',{name:'Open your surprise'}).click();await expect(view.getByRole('heading',{name:'Since our first hello…'})).toBeVisible();expect(Number(await view.locator('.meeting-surprise .magic-digits strong').first().textContent())).toBeGreaterThan(1000);
 const downloadPromise=view.waitForEvent('download');await view.getByRole('button',{name:'Download birthday keepsake'}).click();const download=await downloadPromise;const file=await download.path();const png=await fs.readFile(file!);expect(png.subarray(1,4).toString()).toBe('PNG');expect(png.readUInt32BE(16)).toBe(1200);expect(png.readUInt32BE(20)).toBe(1600);
 await expect(view.locator('.audio-soundtrack iframe')).toHaveCount(0);await expect.poll(()=>view.locator('.audio-soundtrack audio').evaluate((a:HTMLAudioElement)=>!a.paused&&a.currentTime>0.1)).toBe(true);await view.getByRole('button',{name:'Mute music',exact:true}).click();expect(await view.locator('.audio-soundtrack audio').evaluate((a:HTMLAudioElement)=>a.muted)).toBe(true);await view.getByLabel('Change music').selectOption('1');await expect(view.getByLabel('Change music')).toHaveValue('1');await expect.poll(()=>view.locator('.audio-soundtrack audio').evaluate((a:HTMLAudioElement)=>!a.paused&&a.currentTime>0.1)).toBe(true);await view.getByRole('button',{name:'Pause music',exact:true}).click();expect(await view.locator('.audio-soundtrack audio').evaluate((a:HTMLAudioElement)=>a.paused)).toBe(true);expect(await view.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await view.locator('.comic-book').scrollIntoViewIfNeeded();await view.emulateMedia({reducedMotion:'no-preference'});await expect(view.getByRole('button',{name:'Pause cartoon',exact:true})).toBeVisible();expect(await view.locator('.story-one').evaluate(el=>getComputedStyle(el).animationName)).not.toBe('none');await view.getByRole('button',{name:'Pause cartoon',exact:true}).click();expect(await view.locator('.story-one').evaluate(el=>getComputedStyle(el).animationPlayState)).toBe('paused');await view.screenshot({path:'work/magic-comic-mobile.png'});await view.locator('.memory-universe').scrollIntoViewIfNeeded();await view.screenshot({path:'work/magic-stars-mobile.png'});
 expect((await api('GET','/api/sharing/'+site.id+'/capsule')).status()).toBe(401);
 if(local){const identity={'oai-authenticated-user-id':'capsule-recipient-'+site.id,'oai-authenticated-user-email':'recipient@example.test'};const account=await browser.newContext({baseURL:base,extraHTTPHeaders:identity});const journal=await account.newPage();await journal.goto('/s/'+site.id);await journal.getByRole('button',{name:'Draw the curtains'}).click();await journal.getByLabel('Wish for next birthday').fill('Secret wish for future me.');await journal.getByRole('button',{name:'Seal my wish'}).click();await expect(journal.getByText('Wish sealed.',{exact:false})).toBeVisible();const sealed=await (await account.request.get('/api/sharing/'+site.id+'/capsule')).json();expect(sealed.capsules).toHaveLength(1);expect(JSON.stringify(sealed)).not.toContain('Secret wish');expect(sealed.capsules[0].opened).toBe(false);expect((await (await account.request.get('/api/sharing/'+site.id+'/capsule?now=99999999999999')).json()).capsules[0].opened).toBe(false);const repeated=await account.request.post('/api/sharing/'+site.id+'/capsule',{headers:{Origin:origin},data:{body:'Do not replace the sealed wish'}});expect((await repeated.json()).alreadySealed).toBe(true);await account.close();
 const returning=await browser.newContext({baseURL:base,extraHTTPHeaders:identity});const stillSealed=await (await returning.request.get('/api/sharing/'+site.id+'/capsule')).json();expect(stillSealed.capsules[0].id).toBe(sealed.capsules[0].id);expect((await api('GET','/api/sharing/'+site.id+'/capsule',{headers:{...identity,'oai-authenticated-user-id':'different-account'}})).status()).toBe(403);
 // Advance only this disposable local database fixture, never the production clock or data.
 const capsuleId=sealed.capsules[0].id;expect(capsuleId).toMatch(/^[a-f0-9]{64}$/);const hosted=path.resolve('work/public-hosting');execFileSync(process.execPath,['--import','./scripts/sites-env.mjs','./node_modules/wrangler/bin/wrangler.js','d1','execute','DB','--local','--config','dist/server/wrangler.json','--persist-to','.wrangler/state','--command',`UPDATE wish_capsules SET unlock_at=0 WHERE id='${capsuleId}'`],{cwd:hosted,stdio:'pipe'});const opened=await (await returning.request.get('/api/sharing/'+site.id+'/capsule')).json();expect(opened.capsules[0].body).toBe('Secret wish for future me.');await returning.close();
 }else{expect((await api('GET','/api/sharing/'+site.id+'/capsule',{headers:{'oai-authenticated-user-id':'forged','oai-authenticated-user-email':'recipient@example.test'}})).status()).toBe(401);}
 expect((await api('POST','/api/sharing/'+site.id+'?action=unpublish',{headers:own})).status()).toBe(200);await visitor.close();
});
