import {test} from 'node:test';
import assert from 'node:assert/strict';
import {nextBirthday,zonedTime,youtubeVideoId,nextWorld,worlds,capsuleView,durationParts} from '../lib/magic';
test('birthday repeats annually in the selected timezone and handles leap birthdays',()=>{const now=Date.parse('2026-10-10T10:00:00Z');assert.equal(nextBirthday('2000-10-10T00:00',now,'Asia/Kolkata'),Date.parse('2027-10-09T18:30:00Z'));assert.equal(nextBirthday('2000-02-29T00:00',Date.parse('2027-01-01T00:00Z'),'UTC'),Date.parse('2027-02-28T00:00Z'));assert.equal(nextBirthday('',now),null);assert.equal(zonedTime('2026-02-30'),null);assert.equal(zonedTime('2026-03-08T02:30','America/New_York'),null);assert.equal(zonedTime('2026-03-08T03:30','America/New_York'),Date.parse('2026-03-08T07:30Z'));});
test('themes rotate without repeating and duration measures actual elapsed time',()=>{for(let i=0;i<worlds.length;i++)assert.notEqual(nextWorld(i),i);assert.deepEqual(durationParts(90061000),{days:1,hours:1,minutes:1,seconds:1});assert.deepEqual(durationParts(-1),{days:0,hours:0,minutes:0,seconds:0});});
test('YouTube song parser permits supported HTTPS links and rejects executable or spoofed hosts',()=>{for(const url of ['https://youtu.be/M7lc1UVf-VE','https://www.youtube.com/watch?v=M7lc1UVf-VE','https://youtube.com/shorts/M7lc1UVf-VE'])assert.equal(youtubeVideoId(url),'M7lc1UVf-VE');for(const url of ['http://youtu.be/M7lc1UVf-VE','https://youtube.com.evil.test/watch?v=M7lc1UVf-VE','javascript:alert(1)','https://vimeo.com/123'])assert.equal(youtubeVideoId(url),null);});
test('sealed capsule responses never include wish text until the authoritative opening time',()=>{const row={id:'test',body:'Private future wish',created:'2026-10-10T00:00Z',unlockAt:2000};assert.equal('body' in capsuleView(row,1999),false);assert.equal(capsuleView(row,2000).body,row.body);assert.equal(capsuleView(row,1999).opened,false);});

test('hidden cartoon and meeting chapters do not leak their extra content into a snapshot',async()=>{const {newSite}=await import('../lib/model');const {preparePublicationMedia}=await import('../lib/publication-media');const site=newSite();site.comicScenes=['Private scene'];site.storyCharacters=['One','Two'];site.metAt='2020-01-01';site.chapters.find(c=>c.id==='4')!.hidden=true;site.chapters.find(c=>c.id==='10')!.hidden=true;const snapshot=preparePublicationMedia(site,'https://birthday.example');assert.equal(snapshot.comicScenes,undefined);assert.equal(snapshot.metAt,undefined);assert.equal(site.comicScenes[0],'Private scene');});
