"use client";
import {useState} from 'react';
import type {Site} from '@/lib/model';
function lines(ctx:CanvasRenderingContext2D,text:string,width:number) {const result:string[]=[];let line='';for(const word of text.split(/\s+/)){for(const piece of word.match(/.{1,35}/gu)||['']) {const next=(line?line+' ':'')+piece;if(ctx.measureText(next).width>width&&line){result.push(line);line=piece;}else line=next;}}if(line)result.push(line);return result;}
export default function Keepsake({site,accent}:{site:Site;accent:string}) {
 const [status,setStatus]=useState('');
 async function download(){try{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1600;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image export is unavailable.');const gradient=ctx.createLinearGradient(0,0,1200,1600);gradient.addColorStop(0,'#13152b');gradient.addColorStop(1,'#302441');ctx.fillStyle=gradient;ctx.fillRect(0,0,1200,1600);ctx.fillStyle=accent;for(let i=0;i<85;i++){ctx.globalAlpha=.3+(i%5)*.12;ctx.beginPath();ctx.arc(45+(i*137%1110),45+(i*193%1510),i%3+1,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.strokeStyle=accent;ctx.lineWidth=2;ctx.strokeRect(65,65,1070,1470);ctx.textAlign='center';ctx.font='26px Georgia';ctx.fillStyle=accent;ctx.fillText('A LITTLE UNIVERSE, FOREVER YOURS',600,175);ctx.beginPath();ctx.arc(600,350,90,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f7efdf';ctx.font='70px Georgia';ctx.fillText('Happy birthday',600,550);ctx.font='58px Georgia';const name=(site.nickname||site.recipient||'Someone extraordinary').slice(0,100);lines(ctx,name,980).slice(0,3).forEach((line,i)=>ctx.fillText(line,600,635+i*65));const greeting=(site.chapters.find(c=>c.id==='2'&&!c.hidden)?.text||site.chapters.find(c=>c.id==='0'&&!c.hidden)?.text||'Here’s to another beautiful year of wishes, wonder and little moments worth keeping.').slice(0,600);ctx.font='32px Georgia';lines(ctx,greeting,900).slice(0,10).forEach((line,i)=>ctx.fillText(line,600,885+i*48));ctx.font='24px Georgia';ctx.fillStyle=accent;ctx.fillText(new Date().toLocaleDateString(undefined,{dateStyle:'long'}),600,1430);ctx.font='20px Georgia';ctx.fillText('MIDNIGHT MAGIC · A BIRTHDAY KEEPSAKE',600,1480);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Image export failed.')),'image/png'));const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='midnight-magic-keepsake.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Your birthday keepsake is downloaded.');}catch(e){setStatus((e as Error).message);}}
 return <div className="keepsake"><span className="eyebrow">SOMETHING TO KEEP</span><h3>A birthday folded into a little postcard.</h3><p>Keep the greeting, the stars and this moment. Your private diary stays private.</p><button onClick={()=>void download()}>Download birthday keepsake ✦</button>{status&&<p role="status">{status}</p>}</div>;
}
