"use client";
import {useEffect,useRef,useState} from 'react';
import {safeMediaURL,type Media} from '@/lib/model';
export default function PhotoGallery({photos}:{photos:Media[]}){
 const [active,setActive]=useState<number|null>(null),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const el=dialog.current;if(!el)return;if(active===null){if(el.open)el.close();return;}if(!el.open)el.showModal();const before=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=before;};},[active]);
 function next(direction:number){setActive(a=>a===null?null:(a+direction+photos.length)%photos.length);}
 return <div className="memory-wall"><div className="memory-wall-intro"><span className="eyebrow">THE MOMENTS WE KEEP</span><h3>A little museum of us.</h3><p>Some moments deserve their own piece of the sky.</p><span className="wall-orbit" aria-hidden="true">✧</span></div>{photos.length?<div className="memory-mosaic">{photos.map((photo,i)=><button className={'memory-print print-'+(i%8)} key={photo.id} aria-label={'Open memory photo '+(i+1)+(photo.caption?' · '+photo.caption:'')} onClick={()=>setActive(i)}><span className="print-tape" aria-hidden="true"/><span className="print-window"><img loading={i<3?'eager':'lazy'} src={safeMediaURL(photo.src)} alt={photo.caption||'Birthday memory '+(i+1)} style={{objectPosition:`${photo.x}% ${photo.y}%`,transform:`scale(${photo.zoom})`,transformOrigin:`${photo.x}% ${photo.y}%`}}/></span><span className="print-caption"><b>{String(i+1).padStart(2,'0')}</b><span>{photo.caption||'A moment worth keeping'}</span><i aria-hidden="true">♡</i></span></button>)}</div>:<div className="empty-memory-wall"><span aria-hidden="true">☾</span><p>Your memories belong here.</p><small>Add photos in the Photo gallery chapter’s Media tab.</small></div>}<div className="wall-footer"><span aria-hidden="true">✦</span><small>{photos.length?photos.length+' saved moments · tap a photo to step inside':'Every photograph will have its own place.'}</small><span aria-hidden="true">✦</span></div><dialog ref={dialog} className="memory-lightbox" aria-label="Memory photo viewer" onCancel={e=>{e.preventDefault();setActive(null);}} onClose={()=>setActive(null)} onClick={e=>{if(e.target===e.currentTarget)setActive(null);}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();next(1);}if(e.key==='ArrowLeft'){e.preventDefault();next(-1);}}}>{active!==null&&photos[active]&&<div className="lightbox-inner"><button className="lightbox-close" aria-label="Close photo viewer" autoFocus onClick={()=>setActive(null)}>×</button><div className="lightbox-meta"><span className="eyebrow">A MOMENT, HELD FOREVER</span><small>{active+1} / {photos.length}</small></div><figure><img src={safeMediaURL(photos[active].src)} alt={photos[active].caption||'Birthday memory '+(active+1)}/><figcaption>{photos[active].caption||'A moment worth keeping'}</figcaption></figure>{photos.length>1&&<div className="lightbox-nav"><button aria-label="Previous memory photo" onClick={()=>next(-1)}>← Previous</button><span aria-hidden="true">✧</span><button aria-label="Next memory photo" onClick={()=>next(1)}>Next →</button></div>}</div>}</dialog></div>;
}
