"use client";
import WishCapsule from "./WishCapsule";
import {useEffect,useRef,useState} from 'react';
type Entry={id:string;body:string;created:string;updated:string};
export default function RecipientDiary({id}:{id:string}) {
 const [entries,setEntries]=useState<Entry[]>([]);const [state,setState]=useState('loading');const [error,setError]=useState('');const [entryId,setId]=useState('');const [text,setText]=useState('');const [saved,setSaved]=useState('');const [status,setStatus]=useState('');const [retry,setRetry]=useState(0);const queue=useRef(Promise.resolve());
 const path='/api/sharing/'+id+'/diary';
 useEffect(()=>{let active=true;fetch(path,{cache:'no-store'}).then(async r=>{const data=await r.json() as {entries:Entry[];error:string};if(!active)return;if(r.status===401){setState('login');return;}if(!r.ok){setState(r.status===404?'disabled':'denied');setError(data.error);return;}setEntries(data.entries);setId(crypto.randomUUID());setState('ready');}).catch(()=>{if(active){setState('error');setError('Your diary could not be loaded. Refresh to try again.');}});return()=>{active=false;};},[path]);
 useEffect(()=>{if(state!=='ready'||!entryId||text===saved||!text.trim())return;let active=true;setStatus('Saving…');const timer=setTimeout(()=>{queue.current=queue.current.catch(()=>{}).then(async()=>{try{const r=await fetch(path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:entryId,body:text})});const d=await r.json() as {updated:string;error:string};if(!r.ok)throw new Error(d.error);if(active){setSaved(text);setStatus('Saved with date');setEntries(old=>{const previous=old.find(e=>e.id===entryId);return [{id:entryId,body:text,created:previous?.created||d.updated,updated:d.updated},...old.filter(e=>e.id!==entryId)].sort((a,b)=>b.created.localeCompare(a.created));});}}catch(e){if(active)setStatus('Not saved: '+(e as Error).message);}});},1000);return()=>{active=false;clearTimeout(timer);};},[text,saved,entryId,state,path,retry]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(text.trim()&&text!==saved)e.preventDefault();};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[text,saved]);
 if(state==='disabled')return null;
 const pending=!!text.trim()&&text!==saved;
 return <section className="diary chapter" id="personal-diary"><span className="eyebrow">THE NEXT CHAPTER BELONGS TO YOU</span><h2>Your little midnight diary.</h2><p>A place for your days, dreams and next-birthday wish capsule. Private to your login.</p>{state==='loading'?<p>Opening your diary…</p>:state==='login'?<a className="primary pill" target="_top" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/s/'+id+'#personal-diary')}>Sign in with ChatGPT to open your diary</a>:state!=='ready'?<p role="alert">{error}</p>:<><div className="diary-toolbar"><button disabled={pending} onClick={()=>{setId(crypto.randomUUID());setText('');setSaved('');setStatus('');}}>New diary entry</button><a target="_top" href={'/signout-with-chatgpt?return_to='+encodeURIComponent('/s/'+id)}>Sign out</a></div><label>A page from today<textarea rows={8} maxLength={12000} value={text} onChange={e=>setText(e.target.value)} placeholder="Dear diary, today felt like…"/></label><small role="status">{status||'Entries save automatically after you pause typing. Keep this page open until Saved appears.'}</small>{status.startsWith("Not saved:")&&<button onClick={()=>setRetry(r=>r+1)}>Retry saving entry</button>}<WishCapsule id={id}/><div className="diary-pages">{entries.map(e=><article key={e.id}><time dateTime={e.created}>{new Date(e.created).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}</time><p>{e.body}</p><button disabled={pending} onClick={()=>{setId(e.id);setText(e.body);setSaved(e.body);setStatus('Saved with date');}}>Open entry</button></article>)}</div></>}</section>;
}
