"use client";
import {useEffect,useState} from 'react';
import {request} from '@/lib/online';
export default function SharingSettings({id}:{id:string}) {
 const [ready,setReady]=useState(false);const [password,setPassword]=useState('');const [email,setEmail]=useState('');const [protectedStory,setProtected]=useState(false);const [claimed,setClaimed]=useState(false);const [remove,setRemove]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{let active=true;setReady(false);request(id,'GET',undefined,'/settings').then(r=>r.json() as Promise<{protected:boolean;diaryEmail:string;diaryClaimed:boolean}>).then(d=>{if(active){setProtected(d.protected);setEmail(d.diaryEmail);setClaimed(d.diaryClaimed);}}).catch(()=>{}).finally(()=>{if(active)setReady(true);});return()=>{active=false;};},[id]);
 async function save(){if(!ready)return;setBusy(true);setMessage('');try{await request(id,'POST');const result=await (await request(id,'PUT',JSON.stringify({...(password?{password}:{}),removePassword:remove,diaryEmail:email.trim()}),'/settings')).json() as {protected:boolean;diaryEmail:string};setProtected(result.protected);setPassword('');setRemove(false);setMessage('Access settings saved online. Share the password separately from the birthday link.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="access-settings"><span className="eyebrow">A GIFT, JUST FOR THEM</span><h3>Password & private diary</h3>{!ready&&<small>Loading existing access settings…</small>}<p>{protectedStory?'This story is password protected.':'Add a password before sharing your QR or link.'}</p><label>Birthday password<input type="password" disabled={!ready} autoComplete="new-password" minLength={8} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} placeholder={protectedStory?'Leave blank to keep current password':'At least 8 characters'}/></label>{protectedStory&&<label className="check"><input type="checkbox" checked={remove} onChange={e=>setRemove(e.target.checked)}/> Remove password protection</label>}<label>Recipient login email<input type="email" disabled={!ready||claimed} value={email} onChange={e=>setEmail(e.target.value)} placeholder="Recipient’s ChatGPT account email"/></label><small>The diary is private to this recipient’s ChatGPT login, including when they return on another device. Leave email empty to keep the diary disabled. Once they save an entry, the diary cannot be reassigned. Passwords never appear in the QR.</small><button type="button" disabled={!ready||busy||(!!password&&password.length<8)} onClick={()=>void save()}>{busy?'Saving access…':'Save password & diary settings'}</button>{message&&<p role="status">{message}</p>}</div>;
}
