"use client";
import {useEffect,useState} from 'react';
type Capsule={id:string;created:string;unlockAt:string;opened:boolean;body?:string};
export default function WishCapsule({id}:{id:string}) {
 const [capsules,setCapsules]=useState<Capsule[]>([]);const [wish,setWish]=useState('');const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const path='/api/sharing/'+id+'/capsule';
 async function load(){try{const r=await fetch(path,{cache:'no-store'});const d=await r.json() as {capsules:Capsule[];error:string};if(!r.ok)throw new Error(d.error);setCapsules(d.capsules);setReady(true);}catch(e){setMessage((e as Error).message);}}
 useEffect(()=>{void load();},[path]);
 async function seal(){setBusy(true);try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:wish})});const d=await r.json() as {error:string;alreadySealed:boolean};if(!r.ok)throw new Error(d.error);setWish('');setMessage(d.alreadySealed?'Your earlier wish is already sealed and preserved.':'Wish sealed. Future-you has a little surprise waiting.');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const locked=capsules.some(c=>!c.opened);
 useEffect(()=>{if(!ready||!locked)return;const timer=setInterval(()=>void load(),60000);return()=>clearInterval(timer);},[path,ready,locked]);
 return <div className="wish-capsule"><div className="capsule-orb" aria-hidden="true">✦</div><span className="eyebrow">A LETTER TO FUTURE YOU</span><h3>Your next-birthday wish capsule.</h3><p>Seal a wish now. It stays unreadable until your next birthday, even if you change your device clock.</p>{!ready?<button onClick={()=>void load()}>Load wish capsule</button>:!locked?<><label>Wish for next birthday<textarea rows={4} maxLength={2000} value={wish} onChange={e=>setWish(e.target.value)} placeholder="Future me, I hope…"/></label><button className="primary" disabled={busy||!wish.trim()} onClick={()=>void seal()}>{busy?'Sealing…':'Seal my wish ✦'}</button><small>Once sealed, the wish cannot be edited or read early.</small></>:<p>One little wish is safely sealed for future-you.</p>}{message&&<p role="status">{message}</p>}{capsules.map(c=><article key={c.id} className={c.opened?'capsule-open':'capsule-sealed'}><strong>{c.opened?'A wish from your past self':'Sealed until your next birthday'}</strong><time dateTime={c.unlockAt}>{new Date(c.unlockAt).toLocaleString(undefined,{dateStyle:'long',timeStyle:'short'})}</time><p>{c.opened?c.body:'The words are hidden. Let time do its magic.'}</p></article>)}{ready&&<button onClick={()=>void load()}>Check capsule</button>}</div>;
}
