"use client";
import {useEffect,useRef,useState} from 'react';
import {youtubeVideoId} from '@/lib/magic';
type Player={cuePlaylist:(ids:string[],index?:number)=>void;loadPlaylist:(ids:string[],index?:number)=>void;playVideo:()=>void;pauseVideo:()=>void;stopVideo:()=>void;destroy:()=>void;setLoop:(v:boolean)=>void;getPlaylistIndex:()=>number};
type Event={target:Player;data:number};
type Options={videoId:string;width:number;height:number;playerVars:Record<string,string|number>;events:{onReady:(e:Event)=>void;onStateChange:(e:Event)=>void;onError:(e:Event)=>void;onAutoplayBlocked:()=>void}};
declare global {interface Window {YT?:{Player:new(element:HTMLElement,options:Options)=>Player};onYouTubeIframeAPIReady?:()=>void;}}
let apiPromise:Promise<void>|undefined;
function loadAPI(){if(window.YT?.Player)return Promise.resolve();if(apiPromise)return apiPromise;apiPromise=new Promise<void>((resolve,reject)=>{const script=document.createElement('script');const timer=setTimeout(()=>reject(new Error('YouTube took too long to load. Check your connection and try again.')),15000);const previous=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{clearTimeout(timer);previous?.();resolve();};script.src='https://www.youtube.com/iframe_api';script.referrerPolicy='strict-origin-when-cross-origin';script.onerror=()=>{clearTimeout(timer);script.remove();reject(new Error('YouTube could not load. Check your connection and try again.'));};document.head.appendChild(script);}).catch(e=>{apiPromise=undefined;throw e;});return apiPromise;}
export default function YouTubeSoundtrack({songs}:{songs:string[]}) {
 const ids=songs.map(youtubeVideoId).filter((id):id is string=>!!id).slice(0,6);const host=useRef<HTMLDivElement>(null);const player=useRef<Player|null>(null);const generation=useRef(0);const [open,setOpen]=useState(false);const [ready,setReady]=useState(false);const [playing,setPlaying]=useState(false);const [index,setIndex]=useState(0);const [message,setMessage]=useState('');
 useEffect(()=>()=>{generation.current++;player.current?.destroy();},[]);
 async function start(){const current=++generation.current;setOpen(true);setReady(false);setMessage('Loading your soundtrack…');try{await loadAPI();if(current!==generation.current||!host.current)return;const element=document.createElement('div');host.current.replaceChildren(element);player.current=new window.YT!.Player(element,{videoId:ids[0],width:330,height:200,playerVars:{controls:1,playsinline:1,origin:location.origin,autoplay:0},events:{onReady:e=>{if(current!==generation.current)return;e.target.cuePlaylist(ids,0);e.target.setLoop(true);setReady(true);setMessage('Tap Play here or in the YouTube player.');},onStateChange:e=>{if(current!==generation.current)return;setPlaying(e.data===1);setIndex(Math.max(0,e.target.getPlaylistIndex()));if(e.data===1)setMessage('Playing your soundtrack');},onError:e=>{setPlaying(false);setMessage(e.data===153?'YouTube could not verify this page. Open the song on YouTube, or use uploaded audio.':e.data===100?'This song was removed or made private. Choose another song.':'This song cannot play here. Try another song or open it on YouTube.');},onAutoplayBlocked:()=>{setPlaying(false);setMessage('Your browser needs a tap on the YouTube Play button.');}}});}catch(e){if(current===generation.current)setMessage((e as Error).message);}}
 function choose(next:number){const n=(next+ids.length)%ids.length;setIndex(n);if(playing)player.current?.loadPlaylist(ids,n);else player.current?.cuePlaylist(ids,n);player.current?.setLoop(true);}
 function close(){generation.current++;player.current?.stopVideo();player.current?.destroy();player.current=null;setOpen(false);setReady(false);setPlaying(false);}
 if(!ids.length)return null;
 return <aside className={'soundtrack '+(open?'soundtrack-open':'')} aria-label="Birthday soundtrack">{!open?<button className="primary" onClick={()=>void start()}>♫ Open our soundtrack</button>:<><div className="soundtrack-title"><strong>Our little soundtrack</strong><button aria-label="Stop music and close player" onClick={close}>×</button></div><div ref={host} className="yt-stage"/><div className="soundtrack-controls"><button disabled={!ready} aria-label="Previous song" onClick={()=>choose(index-1)}>←</button><button disabled={!ready} onClick={()=>playing?player.current?.pauseVideo():player.current?.playVideo()}>{playing?'Pause music':'Play music'}</button><button disabled={!ready} aria-label="Next song" onClick={()=>choose(index+1)}>→</button><select aria-label="Choose soundtrack song" disabled={!ready} value={index} onChange={e=>choose(Number(e.target.value))}>{ids.map((id,i)=><option value={i} key={i+id}>Song {i+1}</option>)}</select></div><small role="status">{message}</small>{!ready&&<button onClick={()=>{close();void start();}}>Retry loading</button>}<a href={'https://www.youtube.com/watch?v='+ids[index]} target="_blank" rel="noreferrer">Open song on YouTube ↗</a></>}</aside>;
}
